on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.13.4'
    - run: >
        sudo apt update && sudo apt-get -y install 
        build-essential libglu1-mesa-dev libpulse-dev libglib2.0-dev
    - run: docker pull therecipe/qt:linux
      if: false
    - run: export GO111MODULE=off; go get -v github.com/therecipe/qt/cmd/...
      continue-on-error: true
    - name: patch code
      run: |
        echo "package astutil" > $(go env GOPATH)/src/golang.org/x/tools/go/ast/astutil/util.go
    - name: Rebuild project
      run: export GO111MODULE=off; go get -v github.com/therecipe/qt/cmd/...
    - run: $(go env GOPATH)/bin/qtdeploy -docker build linux
    - uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: deploy/
