on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    gover: [1.18.1, 1.19.1, 1.20.1, 1.21.1]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-go@v5
      with:
        go-version: '1.18.1'
    - run: >
        sudo apt update && sudo apt-get -y install 
        build-essential libglu1-mesa-dev libpulse-dev libglib2.0-dev
    - run: docker pull therecipe/qt:linux
      if: false
    - run: |
        export CGO_CFLAGS_ALLOW=".*" 
        export CGO_CXXFLAGS_ALLOW=".*" 
        export CGO_LDFLAGS_ALLOW=".*" 

        export GO111MODULE=off; go get -v github.com/therecipe/qt/cmd/...
        #export GO111MODULE=on; go get -v github.com/therecipe/qt && go install -v -tags=no_env github.com/therecipe/qt/cmd/... && go mod vendor && rm -rf vendor/github.com/therecipe/env_linux_amd64_513 && git clone https://github.com/therecipe/env_linux_amd64_513.git vendor/github.com/therecipe/env_linux_amd64_513 && $(go env GOPATH)/bin/qtsetup
      continue-on-error: true
    - name: patch code
      run: |
        echo "package astutil" > $(go env GOPATH)/src/golang.org/x/tools/go/ast/astutil/util.go
    - name: Rebuild project
      run: export GO111MODULE=off; go get -v github.com/therecipe/qt/cmd/...
    - run: |
        export GO111MODULE=off;
        $(go env GOPATH)/bin/qtdeploy -docker build linux github.com/${{ github.repository }}
    - uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: deploy/
